@api = http://localhost:8080/api/org/@silandro-investors/adventure

{{api}}/all

###
POST {{api}}/new
Content-Type: application/json

{
    "name": "forklift certification"
}


###
GET {{api}}/@forklift-certification-adf87

###
POST {{api}}/@forklift-certification-adf87
Content-Type: application/json

{
    "name": "forklift certification-zestyyyyy"
}

###

POST {{api}}/@forklift-certification-adf87/movestep
Content-Type: application/json

{
    "operation": "swap",
    "adventure": "forklift-certification-adf87",
    "step": "turning-on-the-forklift-eea17",
    "target": "turning-on-the-forklift-a3181"
}