@api = http://localhost:8080/api/user

POST {{api}}/signup
Content-Type: application/json

{
    "username": "michele",
    "password": "michelepazzofolle"
}

###

POST {{api}}/login
Content-Type: application/json

{
    "username": "michele",
    "password": "michelepazzofolle"
}

###

{{api}}/logout