@api = http://localhost:8080/api/org/@silandro-investors

POST http://localhost:8080/api/org/new
Content-Type: application/json

{
    "name": "SILANDRO INVESTORS",
    "secret": "tubre"
}
###

{{api}}/adventure/all

###
POST {{api}}/adventure/new
Content-Type: application/json

{
    "name": "forklift certification brodiecast"
}


###
{{api}}/adventure/@forklift-certification

###
// @silandro-investors
{{api}}

###

{{api}}/meta