@api = http://localhost:8080/api

{{api}}/admin/org/new
Content-Type: application/json

{
    "name": "SILANDRO INVESTORS",
    "secret": "tubre"
}
###

{{api}}/org/@silandro-investors/adventure/all

###
{{api}}/admin/org/@silandro-investors/adventure/new
Content-Type: application/json

{
    "name": "forklift certification brodiecast"
}


###
{{api}}/org/@silandro-investors/adventure/@forklift-certification

###

{{api}}/org/@silandro-investors

###

{{api}}/org/@silandro-investors/meta