@api = http://localhost:8080/api/org/@silandro-investors

POST http://localhost:8080/api/org/new
Content-Type: application/json

{
    "name": "SILANDRO INVESTORS",
    "secret": "tubre"
}

###
// @silandro-investors
{{api}}

###

{{api}}/meta

###
// @silandro-investors
POST {{api}}
Content-Type: application/json

{
    "tag": "SILANDRO INVESTORS TUBRETTI"
}