@api = http://localhost:8080/api/step

POST {{api}}/new
Content-Type: application/json

{
    "name": "turning on the forklift",
    "description": "learn how to turn on your forklift",
    "content": {"en_us": "bro take the key and put it in 🤑"},
    "category": "lesson",
    "xp_award": 233333,
    "coins_award": 30,
    "energy_cost": 1,
    "parent": "adv:forklift-certification-adf87",
    "branch_index": 0
}

###
GET {{api}}/@forkliftstep1-123456

###
GET {{api}}/many
Content-Type: application/json

{
    "items": ["turning-on-the-forklift-5b20b", "turning-on-the-forklift-aafb5"]
}

###
POST {{api}}/@turning-on-the-forklift-5b20b
Content-Type: application/json

{
    "name": "gente educata 2025"
}