@api = http://localhost:8080/api/user

{{api}}/me

###

POST {{api}}/me/settings/edit
Content-Type: application/json

{
    "theme": "workshop"
}

###

POST {{api}}/org/join/d629b8

###

POST {{api}}/org/leave/@silandro-investors

###

GET {{api}}/org/joined

###

GET {{api}}/org/joined/tags