# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DB_CONNECTION: mongodb://root:root@mongo:27017/
  JWT_SECRET: github
  DB_USERNAME: root
  DB_PASSWORD: root
  DBDASH_USERNAME: admin
  DBDASH_PASSWORD: pass
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

  test:
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    
   

    - name: Run tests
      run: go test ./...

      
      
